[tool.poetry]
name = "birdcall-distribution"
version = "0.1.0"
description = ""
authors = ["Anthony Miyaguchi <acmiyaguchi@gatech.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
dask = "^2022.9.0"
rioxarray = "^0.12.0"
xarray = "^2022.6.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.4.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
